### ISSUE TITLE
[minor] - Nombre de función

### ISSUE THREAD

**Issue by edgarbonillag** [ale1313/challenge-nextdots-2019#1]
[minor] - Nada grave, sólo usar nombres más descriptivos. Ej: `getDrinks`, `fetchDrinks´, `getDrinksList`, etc...
https://github.com/ale1313/challenge-nextdots-2019/blob/846518f5658f8940a5c310bd1cf1d0e91e36d365/src/actions/fetch.ts#L25

**Comment by ale1313** [comment]
Cambiados los nombres. Gracias!
