### ISSUE TITLE
Preguntar en la screen

### ISSUE THREAD

**Issue by LcsGrz** [ale1313/challenge-nextdots-2019#11]
https://github.com/ale1313/challenge-nextdots-2019/blob/282c144e80d86f7c309f806d95e959bde69e9e6c/src/actions/getDrinks.ts#L32

No se si sea bueno mezclar las cosas, creeria que redux deberia estar en la screen y preguntar por ese atributo directamente ahi y verificar si hacer la llamada al action o no

**Comment by ale1313** [comment]
Ya cambié de lugar los atributos, gracias
