### ISSUE TITLE
Constantes

### ISSUE THREAD

**Issue by LcsGrz** [ale1313/challenge-nextdots-2019#13]
https://github.com/ale1313/challenge-nextdots-2019/blob/282c144e80d86f7c309f806d95e959bde69e9e6c/src/components/DefaultText/DefaultText.tsx#L11

Siempre que el valor no se modifique, usa `const`

**Comment by ale1313** [comment]
Me confundí con el value y creí que cambiaba jaja, ahí lo arreglé
