### ISSUE TITLE
Colores en un archivo

### ISSUE THREAD

**Issue by LcsGrz** [ale1313/challenge-nextdots-2019#14]
https://github.com/ale1313/challenge-nextdots-2019/blob/282c144e80d86f7c309f806d95e959bde69e9e6c/src/components/SearchButton/SearchButton.tsx#L15

No es importante para ahora, pero para tener en cuenta

Los colores deberian ir en un archivo dentro de 
`src -> theme -> colors.ts`

ej:

`export const {red:"red"}`

**Comment by ale1313** [comment]
Ya centralicé los colores en un archivo, gracias
