### ISSUE TITLE
[minor] - Nombres más descriptivos

### ISSUE THREAD

**Issue by edgarbonillag** [ale1313/challenge-nextdots-2019#2]
Nada grave acá tampoco.
Sólo usar por ej: `GET_DRINKS_START` para sólo con el nombre ya tener una idea de qué hace la acción. En este challenge no tiene mucho problema pero en apps más grandes esto es algo muy importante.

https://github.com/ale1313/challenge-nextdots-2019/blob/846518f5658f8940a5c310bd1cf1d0e91e36d365/src/actions/types.ts#L1

**Comment by ale1313** [comment]
Solucionado, saludos
