### ISSUE TITLE
[critical] - Esto no debería estar conectado con redux

### ISSUE THREAD

**Issue by edgarbonillag** [ale1313/challenge-nextdots-2019#5]
https://github.com/ale1313/challenge-nextdots-2019/blob/846518f5658f8940a5c310bd1cf1d0e91e36d365/src/components/DrinksRenderer/DrinksRenderer.tsx#L69

Idealmente las únicas que deberían conectarse con redux con las screen. Este archivo es un componente. Es mejor programarlo para que reciba como prop la lista de drinks y que toda la conexión con redux se haga en la screen `DrinksList` y que desde esta screen se le pasen la lista de drinks como prop a este componente.

**Comment by ale1313** [comment]
Ya le pasé el state a través de props. Saludos!
