### ISSUE TITLE
[critical] - Usar destructuring para 'props' y para 'state'

### ISSUE THREAD

**Issue by edgarbonillag** [ale1313/challenge-nextdots-2019#7]
https://github.com/ale1313/challenge-nextdots-2019/blob/e5c151e9910b82000e8d0d199aa1a7182d641dbb/src/screens/main/drinksList/DrinksList.tsx#L65

Ej: 
`const { showResults } = this.state;`
`const { navigation } = this.props;`

NOTA: Esto mismo en todos los otros lugares o funciones que se usen state o props.

**Comment by ale1313** [comment]
Destructuring implementado en el último commit, saludos
