### ISSUE TITLE
[critical] - Nombres más descriptivos

### ISSUE THREAD

**Issue by edgarbonillag** [ale1313/challenge-nextdots-2019#8]
https://github.com/ale1313/challenge-nextdots-2019/blob/68f2c6d604d5aa9e6f7f2c14de68dd10e5f9ec4a/src/reducers/fetchReducer.ts#L17

En este caso por ejemplo el archivo se puede llamar `drinksReducer`porque aquí se almacena todo lo relacionado con los drinks.

Así mismo se puede llamar la función principal del reducer.

**Comment by ale1313** [comment]
Solucionado, saludos
