### ISSUE TITLE
Spread operator

### ISSUE THREAD

**Issue by LcsGrz** [ale1313/challenge-nextdots-2019#9]
https://github.com/ale1313/challenge-nextdots-2019/blob/282c144e80d86f7c309f806d95e959bde69e9e6c/src/reducers/drinksReducer.ts#L25

Si vemos las buenas practicas, es mejor hacer esto mismo con el spread operator

VER: https://github.com/airbnb/javascript#objects--rest-spread

**Comment by ale1313** [comment]
Antes lo hacía de esa manera pero Javi me recomendó que utilizara `Object.assign()`, personalmente prefiero utilizar el spread ya que el código queda más limpio
